In [48]:
import numpy as np
import scipy.stats as stats

In [49]:
scuccesses_basline = [29,	29,	28,	25,	23,	22,	20,	20,	20,	23,	24,	25]
successes_speedy = [24,	24,	18,	14,	15,	18,	16,	15,	18,	17,	24,	24]
N = 31
alpha = 0.05
number_total_tests = 12
alpha_bonf = alpha/number_total_tests

In [50]:
alpha_bonf

0.004166666666666667

In [51]:
x1 = scuccesses_basline[0]
x2 = successes_speedy[0]
n1=N
n2=N

In [52]:
p1=x1/n1
p2=x2/n2

In [53]:
p_hat = (x1+x2)/(n1+n2)
z_obs = (p1-p2)/np.sqrt(p_hat*(1-p_hat)*(1/n1+1/n2))

In [54]:
p_val = 2*(1-stats.norm.cdf(abs(z_obs)))

In [55]:
p_val

0.07144629982300987

In [56]:
scuccesses_basline_np = np.array([29,	29,	28,	25,	23,	22,	20,	20,	20,	23,	24,	25])
successes_speedy_np = np.array([24,	24,	18,	14,	15,	18,	16,	15,	18,	17,	24,	24])

In [57]:
n1 = N
n2 = N

In [58]:
p1 = scuccesses_basline_np/n1
p2 = successes_speedy_np/n2

p_hat = (scuccesses_basline_np+successes_speedy_np)/(n1+n2)
z_obs = (p1-p2)/np.sqrt(p_hat*(1-p_hat)*(1/n1+1/n2))
p_val = 2*(1-stats.norm.cdf(abs(z_obs)))


for i in range(12):
    print(f'at position{i+1} z_obs: {z_obs[i]} p_val: {p_val[i]}')

at position1 z_obs: 1.8026302701844668 p_val: 0.07144629982300987
at position2 z_obs: 1.8026302701844668 p_val: 0.07144629982300987
at position3 z_obs: 2.90239780930841 p_val: 0.00370317957270605
at position4 z_obs: 2.891960177419719 p_val: 0.003828464699555889
at position5 z_obs: 2.085875641782716 p_val: 0.03698988925642266
at position6 z_obs: 1.0617310051386497 p_val: 0.2883578195538239
at position7 z_obs: 1.0294799948658837 p_val: 0.30325417567379365
at position8 z_obs: 1.2807074764409083 p_val: 0.2002964327274226
at position9 z_obs: 0.5214689104456784 p_val: 0.6020401577875107
at position10 z_obs: 1.592596507707975 p_val: 0.1112507374893188
at position11 z_obs: 0.0 p_val: 1.0
at position12 z_obs: 0.3119795509138105 p_val: 0.7550560642768092

In [59]:
import pandas as pd

In [60]:
df = pd.DataFrame({
    'Position': range(1, 13),
    'Baseline Successes': scuccesses_basline_np,
    'Speedy Sucesses': successes_speedy_np,
    'Difference(Baseline and Speedy)': scuccesses_basline_np-successes_speedy_np,
    # 'z-statistic': z_obs,
    # 'p-value': p_val,
    'Speedy Significant Difference': p_val<alpha_bonf
})

In [61]:
df

,Position,Baseline Successes,Speedy Sucesses,Difference(Baseline and Speedy),Speedy Significant Difference
0,1,29,24,5,False
1,2,29,24,5,False
2,3,28,18,10,True
3,4,25,14,11,True
4,5,23,15,8,False
5,6,22,18,4,False
6,7,20,16,4,False
7,8,20,15,5,False
8,9,20,18,2,False
9,10,23,17,6,False
10,11,24,24,0,False
11,12,25,24,1,False

In [62]:
successes_run_np = np.array([24,	22,	17,	18,	17,	13,	9,	11,	8,	14,	9,	13])

In [63]:
p_run = successes_run_np/n2

p_hat = (scuccesses_basline_np+ successes_run_np)/(n1+n2)
z_obs_2 = (p1-p_run)/np.sqrt(p_hat*(1-p_hat)*(1/n1+1/n2))
p_val_2 = 2*(1-stats.norm.cdf(abs(z_obs_2)))


for i in range(12):
    print(f'at position{i+1} z_obs: {z_obs_2[i]} p_val: {p_val_2[i]}')

at position1 z_obs: 1.8026302701844668 p_val: 0.07144629982300987
at position2 z_obs: 2.327086111056259 p_val: 0.019960682579199807
at position3 z_obs: 3.1315389104579907 p_val: 0.0017389274138499555
at position4 z_obs: 1.9283366542546403 p_val: 0.0538132654285286
at position5 z_obs: 1.592596507707975 p_val: 0.1112507374893188
at position6 z_obs: 2.3052734575936356 p_val: 0.021151263088184713
at position7 z_obs: 2.7998357915724474 p_val: 0.005112860826270715
at position8 z_obs: 2.286002286003429 p_val: 0.022254124823099186
at position9 z_obs: 3.0623767339281107 p_val: 0.0021958689496188732
at position10 z_obs: 2.330062056939512 p_val: 0.01980287146181947
at position11 z_obs: 3.8179578975987916 p_val: 0.0001345608818374977
at position12 z_obs: 3.1288134626740733 p_val: 0.0017551369206376677

In [64]:
df['Run Successes'] = successes_run_np
df['Difference(Baseline and Run)'] = scuccesses_basline_np-successes_run_np
# df['z--statistic'] = z_obs_2
# df['p--value'] = p_val_2
df['Run significant difference'] = p_val_2<alpha_bonf

In [65]:
df

,Position,Baseline Successes,Speedy Sucesses,Difference(Baseline and Speedy),Speedy Significant Difference,Run Successes,Difference(Baseline and Run),Run significant difference
0,1,29,24,5,False,24,5,False
1,2,29,24,5,False,22,7,False
2,3,28,18,10,True,17,11,True
3,4,25,14,11,True,18,7,False
4,5,23,15,8,False,17,6,False
5,6,22,18,4,False,13,9,False
6,7,20,16,4,False,9,11,False
7,8,20,15,5,False,11,9,False
8,9,20,18,2,False,8,12,True
9,10,23,17,6,False,14,9,False
10,11,24,24,0,False,9,15,True
11,12,25,24,1,False,13,12,True

run has an effect on recency, as there is a significant difference in the last letters, as baseline was better(+ve diff)

In [66]:
succeses_pause_np = np.array([25,	23,	22,	15,	19,	17,	13,	14,	9,	15,	20,	24])

In [67]:
p_pause = succeses_pause_np/n2

p_hat = (scuccesses_basline_np+ succeses_pause_np)/(n1+n2)
z_obs_3 = (p1-p_pause)/np.sqrt(p_hat*(1-p_hat)*(1/n1+1/n2))
p_val_3 = 2*(1-stats.norm.cdf(abs(z_obs_3)))


for i in range(12):
    print(f'at position{i+1} z_obs: {z_obs_3[i]} p_val: {p_val_3[i]}')

at position1 z_obs: 1.5153535218873175 p_val: 0.12968290097307378
at position2 z_obs: 2.0717885249966246 p_val: 0.03828516729354514
at position3 z_obs: 1.9287301521985902 p_val: 0.05376437097506104
at position4 z_obs: 2.6543275128466237 p_val: 0.007946665551842091
at position5 z_obs: 1.0867163295692124 p_val: 0.27716219499733374
at position6 z_obs: 1.3145273533726005 p_val: 0.18866879927266078
at position7 z_obs: 1.7817136855461027 p_val: 0.07479593398852669
at position8 z_obs: 1.5311883669640551 p_val: 0.12572284502729558
at position9 z_obs: 2.7998357915724474 p_val: 0.005112860826270715
at position10 z_obs: 2.085875641782716 p_val: 0.03698988925642266
at position11 z_obs: 1.119162746219357 p_val: 0.2630707152767928
at position12 z_obs: 0.3119795509138105 p_val: 0.7550560642768092

In [68]:
df['Pause Successes'] = succeses_pause_np
df['Difference(Baseline and Pause)'] = scuccesses_basline_np-succeses_pause_np
# df['z---statistic'] = z_obs_3
# df['p---value'] = p_val_3
df['Pause significant difference'] = p_val_3<alpha_bonf

In [69]:
df

,Position,Baseline Successes,Speedy Sucesses,Difference(Baseline and Speedy),Speedy Significant Difference,Run Successes,Difference(Baseline and Run),Run significant difference,Pause Successes,Difference(Baseline and Pause),Pause significant difference
0,1,29,24,5,False,24,5,False,25,4,False
1,2,29,24,5,False,22,7,False,23,6,False
2,3,28,18,10,True,17,11,True,22,6,False
3,4,25,14,11,True,18,7,False,15,10,False
4,5,23,15,8,False,17,6,False,19,4,False
5,6,22,18,4,False,13,9,False,17,5,False
6,7,20,16,4,False,9,11,False,13,7,False
7,8,20,15,5,False,11,9,False,14,6,False
8,9,20,18,2,False,8,12,True,9,11,False
9,10,23,17,6,False,14,9,False,15,8,False
10,11,24,24,0,False,9,15,True,20,4,False
11,12,25,24,1,False,13,12,True,24,1,False